/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansUsuario;
import modeloBeans.ModeloTabela;
import modeloConection.ConectarNoBanco;
import modeloDao.DaoUsuario;

/**
 *
 * @author User
 */
public class FormUsuario extends javax.swing.JFrame {
    ConectarNoBanco connBanco = new ConectarNoBanco();
    BeansUsuario mod = new BeansUsuario();
    DaoUsuario control = new DaoUsuario();
    int flag = 0;
    
    public FormUsuario() {
        initComponents();
        preencherTabelaUsuario("select *from usuarios order by nome_usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldConfirmarSenha = new javax.swing.JPasswordField();
        jLabelConfirmarSenha = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jLabelCodUsuario = new javax.swing.JLabel();
        jTextFieldCodUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonVoltarr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Therapias - Habilitação Pediátrica");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("CADASTRO DE USUÁRIOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 10, 420, 50);

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(70, 160, 100, 30);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(70, 200, 100, 30);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(70, 320, 100, 30);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(70, 240, 100, 30);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(70, 280, 100, 30);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelUsuario.setText("Usuário:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(310, 110, 50, 16);

        jTextFieldUsuario.setEnabled(false);
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(370, 100, 280, 30);

        jPasswordFieldSenha.setEnabled(false);
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(370, 150, 200, 30);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(320, 160, 41, 16);

        jPasswordFieldConfirmarSenha.setEnabled(false);
        jPasswordFieldConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfirmarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldConfirmarSenha);
        jPasswordFieldConfirmarSenha.setBounds(700, 150, 180, 30);

        jLabelConfirmarSenha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelConfirmarSenha.setText("Confirma Senha:");
        getContentPane().add(jLabelConfirmarSenha);
        jLabelConfirmarSenha.setBounds(590, 160, 97, 16);

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelTipo.setText("Tipo:");
        getContentPane().add(jLabelTipo);
        jLabelTipo.setBounds(330, 200, 30, 16);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------------", "Administrativo", "Direção", "Financeiro", "Recepção", "Terapeuta", "ADS" }));
        jComboBoxTipo.setEnabled(false);
        getContentPane().add(jComboBoxTipo);
        jComboBoxTipo.setBounds(370, 190, 120, 30);
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(400, 300, 260, 30);

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(670, 300, 100, 30);

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(350, 360, 460, 100);

        jLabelCodUsuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelCodUsuario.setText("Cod.:");
        getContentPane().add(jLabelCodUsuario);
        jLabelCodUsuario.setBounds(680, 110, 31, 16);

        jTextFieldCodUsuario.setEnabled(false);
        jTextFieldCodUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodUsuario);
        jTextFieldCodUsuario.setBounds(720, 100, 60, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/foto.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 30, 110, 110);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(270, 260, 610, 5);

        jButtonVoltarr.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonVoltarr.setText("Voltar");
        jButtonVoltarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarrActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarr);
        jButtonVoltarr.setBounds(70, 400, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_adjacentes.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 890, 480);

        setSize(new java.awt.Dimension(906, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfirmarSenhaActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldUsuario.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldConfirmarSenha.setEnabled(true);
        jComboBoxTipo.setEnabled(true);        
        jTextFieldPesquisar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonPesquisar.setEnabled(false); 
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jTextFieldUsuario.setText("");
        jComboBoxTipo.setSelectedItem("");
        jPasswordFieldSenha.setText("");
        jPasswordFieldConfirmarSenha.setText("");        
        jTextFieldPesquisar.setText("");
        jTextFieldCodUsuario.setText("");
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            if(jTextFieldUsuario.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo USUÁRIO para continuar");
                jTextFieldUsuario.requestFocus();                
            }else if(jPasswordFieldSenha.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo SENHA para continuar");
                jPasswordFieldSenha.requestFocus();
            }else if(jPasswordFieldConfirmarSenha.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo CONFIRMAR SENHA para continuar");
                jPasswordFieldConfirmarSenha.requestFocus();           
            }else 
            if(jPasswordFieldSenha.getText().equals(jPasswordFieldConfirmarSenha.getText())){
                if(flag ==1){
                    mod.setNomeUsuario(jTextFieldUsuario.getText());
                    mod.setSenhaUsuario(jPasswordFieldSenha.getText());
                    mod.setTipoUsuario((String)jComboBoxTipo.getSelectedItem());            
                    control.Salvar(mod);
                    preencherTabelaUsuario("select *from usuarios order by nome_usuario");
                    jTextFieldUsuario.setText("");
                    jPasswordFieldSenha.setText("");
                    jPasswordFieldConfirmarSenha.setText("");
                    jComboBoxTipo.setSelectedItem("");            
                    jTextFieldPesquisar.setText("");
                    jTextFieldUsuario.setEnabled(false);
                    jPasswordFieldSenha.setEnabled(false);
                    jPasswordFieldConfirmarSenha.setEnabled(false);
                    jComboBoxTipo.setEnabled(false);            
                    jTextFieldPesquisar.setEnabled(true);
                    jButtonSalvar.setEnabled(false);
                    jButtonCancelar.setEnabled(false);
                    jButtonPesquisar.setEnabled(true);
                    jButtonNovo.setEnabled(true);
                    jTextFieldCodUsuario.setText("");
                    jButtonCancelar.setEnabled(false);
                }else{
                mod.setCodUsuario(Integer.parseInt(jTextFieldCodUsuario.getText()));
                mod.setNomeUsuario(jTextFieldUsuario.getText());
                mod.setSenhaUsuario(jPasswordFieldSenha.getText());
                mod.setTipoUsuario((String)jComboBoxTipo.getSelectedItem());                
                control.Editar(mod);
                preencherTabelaUsuario("select *from usuarios order by nome_usuario");
                jTextFieldCodUsuario.setText("");
                jTextFieldUsuario.setText("");
                jPasswordFieldSenha.setText("");
                jPasswordFieldConfirmarSenha.setText("");
                jTextFieldPesquisar.setText("");
                jComboBoxTipo.setSelectedItem("");                
                jTextFieldUsuario.setEnabled(false);
                jPasswordFieldSenha.setEnabled(false);
                jPasswordFieldConfirmarSenha.setEnabled(false);
                jComboBoxTipo.setEnabled(false);                
                jTextFieldPesquisar.setEnabled(true);
                jButtonPesquisar.setEnabled(true);
                jButtonSalvar.setEnabled(false);
                jButtonNovo.setEnabled(true);
                jButtonCancelar.setEnabled(false);
                jButtonEditar.setEnabled(false);
                }    
            }else{
                JOptionPane.showMessageDialog(rootPane, "Senhas não correspondem!");
            }              
            
        } catch (SQLException ex) {
            //Logger.getLogger(FormFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldCodUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodUsuarioActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisar(jTextFieldPesquisar.getText());
        BeansUsuario model = control.buscaUsuario(mod);
        jTextFieldCodUsuario.setText(String.valueOf(model.getCodUsuario()));
        jTextFieldUsuario.setText(model.getNomeUsuario());          
        jPasswordFieldSenha.setText(model.getSenhaUsuario());
        jPasswordFieldConfirmarSenha.setText(model.getSenhaUsuario());
        jComboBoxTipo.setSelectedItem(model.getTipoUsuario());        
        jButtonExcluir.setEnabled(!true);
        jButtonEditar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        preencherTabelaUsuario("select *from usuarios where nome_usuario like'%" + jTextFieldPesquisar.getText() +"%'");
        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldUsuario.setEnabled(!true);
        jPasswordFieldSenha.setEnabled(!true);
        jPasswordFieldConfirmarSenha.setEnabled(!true);
        jComboBoxTipo.setEnabled(!true);        
        jTextFieldPesquisar.setEnabled(true);        
        jButtonPesquisar.setEnabled(true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldUsuario.setText("");
        jPasswordFieldSenha.setText("");
        jPasswordFieldConfirmarSenha.setText("");
        jComboBoxTipo.setSelectedItem("");                
        jTextFieldCodUsuario.setText("");
        jTextFieldPesquisar.setText("");        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldUsuario.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldConfirmarSenha.setEnabled(true);
        jComboBoxTipo.setEnabled(true);        
        jTextFieldPesquisar.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTabelaUsuario("select *from usuarios");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta= 0;
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
            if(resposta == JOptionPane.YES_OPTION){
                mod.setCodUsuario(Integer.parseInt(jTextFieldCodUsuario.getText()));
                control.Excluir(mod);
                preencherTabelaUsuario("select *from usuarios order by nome_usuario");
                jTextFieldUsuario.setText("");
                jPasswordFieldSenha.setText("");
                jPasswordFieldConfirmarSenha.setText("");
                jComboBoxTipo.setSelectedItem("");                
                jTextFieldCodUsuario.setText("");
                jTextFieldPesquisar.setText("");        
                jButtonSalvar.setEnabled(false);
                jButtonCancelar.setEnabled(false);
                jButtonEditar.setEnabled(false);
                jButtonNovo.setEnabled(true);
                jButtonExcluir.setEnabled(false);  
        }    
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMouseClicked
        String nome_usuario = "" + jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 1);
        connBanco.conexao();
        connBanco.executaSQL("select *from usuarios where nome_usuario='"+nome_usuario+"'");
        try {
            connBanco.rs.first();
            jTextFieldCodUsuario.setText(String.valueOf(connBanco.rs.getInt("cod_usuario")));
            jTextFieldUsuario.setText(connBanco.rs.getString("nome_usuario")); 
            jComboBoxTipo.setSelectedItem(connBanco.rs.getString("tipo_usuario")); 
            jPasswordFieldSenha.setText(connBanco.rs.getString("senha_usuario"));
            jPasswordFieldConfirmarSenha.setText(connBanco.rs.getString("senha_usuario"));
            connBanco.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar os dados!\nERRO:" + ex);
        }
        connBanco.desconecta();
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jTextFieldCodUsuario.setEnabled(false);
        jTextFieldUsuario.setEnabled(false);
        jPasswordFieldSenha.setEnabled(false);
        jPasswordFieldConfirmarSenha.setEnabled(false);
        jComboBoxTipo.setEnabled(false);
    }//GEN-LAST:event_jTableUsuarioMouseClicked

    private void jButtonVoltarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarrActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarrActionPerformed

    public void preencherTabelaUsuario(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[] {"Cód.","Usuário","Tipo"};
        connBanco.conexao();
        connBanco.executaSQL(Sql);
        try{
            connBanco.rs.first();
            do{
                dados.add(new Object[]{connBanco.rs.getInt("cod_usuario"), connBanco.rs.getString("nome_usuario"), connBanco.rs.getString("tipo_usuario")});
                
            }while(connBanco.rs.next());
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayListUsu" + ex);
        }
        ModeloTabela modelo= new ModeloTabela(dados, colunas);
        
        jTableUsuario.setModel(modelo);
        jTableUsuario.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableUsuario.getColumnModel().getColumn(0).setResizable(false);
        jTableUsuario.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTableUsuario.getColumnModel().getColumn(1).setResizable(false);        
        jTableUsuario.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableUsuario.getColumnModel().getColumn(2).setResizable(false);
        jTableUsuario.getTableHeader().setReorderingAllowed(false);
        jTableUsuario.setAutoResizeMode(jTableUsuario.AUTO_RESIZE_OFF);
        jTableUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        connBanco.desconecta();
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JButton jButtonVoltarr;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCodUsuario;
    private javax.swing.JLabel jLabelConfirmarSenha;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldConfirmarSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField jTextFieldCodUsuario;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
