/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import static java.awt.SystemColor.control;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansPacientes;
import modeloBeans.ModeloTabela;
import modeloConection.ConectarNoBanco;
import modeloDao.DaoPacientes;

/**
 *
 * @author User
 */
public class FormPesquisaPaciente extends javax.swing.JFrame {
    ConectarNoBanco connBanco = new ConectarNoBanco();
    BeansPacientes mod = new BeansPacientes();
    DaoPacientes control = new DaoPacientes();
   
    /**
     * Creates new form FormPesquisaPaciente
     */
    public FormPesquisaPaciente() {
        initComponents();
        preencherTabela("select *from pacientes order by nome_paciente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPesquisarPacientes = new javax.swing.JButton();
        jTextFieldPesquisarPacientes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisaPaciente = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonPesquisarPacientes.setText("Pesquisar");
        jButtonPesquisarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisarPacientes);
        jButtonPesquisarPacientes.setBounds(640, 110, 90, 30);

        jTextFieldPesquisarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisarPacientes);
        jTextFieldPesquisarPacientes.setBounds(450, 110, 170, 30);

        jTablePesquisaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePesquisaPaciente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 190, 680, 100);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(60, 160, 80, 30);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(60, 200, 80, 30);

        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(60, 250, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_adjacentes.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 970, 550);

        setSize(new java.awt.Dimension(973, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarPacientesActionPerformed
        mod.setPesquisar(jTextFieldPesquisarPacientes.getText());
        BeansPacientes model = control.buscaPacientes(mod);
//        jTextFieldNomeP.setText(model.getNome());  
//        jTextFieldCodFuncionario.setText(String.valueOf(model.getCodigo()));
//        jFormattedTextFieldTelefoneFuncionario.setText(String.valueOf(model.getTelefone()));
//        jTextFieldRgFuncionario.setText(String.valueOf(model.getRg()));
//        jFormattedTextFieldCpfFuncionario.setText(String.valueOf(model.getCpf()));
//        jFormattedTextFieldData_de_Nascimento.setText(String.valueOf(model.getDatadenascimento()));
//        jComboBoxProfissaoFuncionario.setSelectedItem(model.getProfissao());
//        jTextFieldConselhoFuncionario.setText(String.valueOf(model.getConselho()));
//        jButtonEditar.setEnabled(true);
//        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarPacientesActionPerformed

    private void jTextFieldPesquisarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarPacientesActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        FormPacientes tela = new FormPacientes();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    public void preencherTabela(String Sql){
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPesquisaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisarPacientes;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisaPaciente;
    private javax.swing.JTextField jTextFieldPesquisarPacientes;
    // End of variables declaration//GEN-END:variables
}
