/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansAgendamento;
import modeloBeans.BeansPacientes;
import modeloBeans.ModeloTabela;
import modeloConection.ConectarNoBanco;
import modeloDao.DaoAgendamento;
import modeloDao.DaoPacientes;

/**
 *
 * @author User
 */
public class FormAgendamento extends javax.swing.JFrame {
    ConectarNoBanco connBanco = new ConectarNoBanco();
    BeansPacientes mod = new BeansPacientes();
    BeansAgendamento modAge = new BeansAgendamento();
    DaoPacientes control = new DaoPacientes();
    DaoAgendamento controlAge = new DaoAgendamento();
    
    /**
     * Creates new form FormAgendamento
     */
    public FormAgendamento() {
        initComponents();
        preencherComboTerapeutas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarPaciente = new javax.swing.JTable();
        jComboBoxTerapia = new javax.swing.JComboBox<>();
        jComboBoxTerapeuta = new javax.swing.JComboBox<>();
        jComboBoxHorario = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtonAdcionar = new javax.swing.JButton();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAgendamento = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelNomePaciente = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jTextFieldCod = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(410, 110, 220, 30);

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(640, 110, 100, 30);

        jTablePesquisarPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisarPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePesquisarPaciente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 160, 590, 90);

        jComboBoxTerapia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--TERAPIA--", "Fisioterapia", "Ter. Ocupacional", "Fonoaudiologia", "Psicologia", "Therasuit", "Est. Visual", "Musicoterapia", " " }));
        getContentPane().add(jComboBoxTerapia);
        jComboBoxTerapia.setBounds(290, 370, 110, 30);

        jComboBoxTerapeuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxTerapeuta);
        jComboBoxTerapeuta.setBounds(410, 370, 110, 30);

        jComboBoxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--HORA--", "07:00", "08:00", "09:00", "10:00", "11:00" }));
        getContentPane().add(jComboBoxHorario);
        jComboBoxHorario.setBounds(640, 370, 100, 30);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(270, 280, 590, 5);

        jButtonAdcionar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonAdcionar.setText("Adcionar");
        jButtonAdcionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdcionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdcionar);
        jButtonAdcionar.setBounds(750, 370, 110, 30);

        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--DIA--", "Seg", "Ter", "Qua", "Qui", "Sex" }));
        getContentPane().add(jComboBoxDia);
        jComboBoxDia.setBounds(530, 370, 100, 30);

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Agendamento");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 10, 250, 40);

        jTableAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableAgendamento);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(320, 430, 490, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/foto.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 40, 130, 130);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Paciente:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 310, 70, 30);

        jLabelNomePaciente.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(jLabelNomePaciente);
        jLabelNomePaciente.setBounds(490, 310, 220, 30);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonEditar.setText("Editar");
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(70, 230, 90, 30);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonExcluir.setText("Excluir");
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(70, 270, 90, 30);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(70, 310, 90, 30);

        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(70, 380, 90, 30);

        jTextFieldCod.setText("jTextField1");
        getContentPane().add(jTextFieldCod);
        jTextFieldCod.setBounds(300, 320, 59, 20);

        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_adjacentes.jpg"))); // NOI18N
        getContentPane().add(jLabel);
        jLabel.setBounds(0, 0, 880, 550);

        setSize(new java.awt.Dimension(893, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisar(jTextFieldPesquisar.getText());
        BeansPacientes model = control.buscaPacientes(mod);        
        preencherTabelaPacientes("select *from pacientes where nome_paciente like'%" + jTextFieldPesquisar.getText() +"%'");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTablePesquisarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisarPacienteMouseClicked
        String nome_paciente = "" + jTablePesquisarPaciente.getValueAt(jTablePesquisarPaciente.getSelectedRow(), 1);
        connBanco.conexao();
        connBanco.executaSQL("select *from pacientes where nome_paciente='"+nome_paciente+"'");
        try {
            connBanco.rs.first();
            jLabelNomePaciente.setText(connBanco.rs.getString("nome_paciente")); 
            connBanco.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar os dados!\nERRO:" + ex);
        }
        connBanco.desconecta();        
    }//GEN-LAST:event_jTablePesquisarPacienteMouseClicked

    private void jButtonAdcionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdcionarActionPerformed
                        
//        try {            
//            modAge.setTerapia((String)jComboBoxTerapia.getSelectedItem());
//            modAge.setDia((String)jComboBoxDia.getSelectedItem());
//            modAge.setHora((String)jComboBoxHorario.getSelectedItem());                        
//            modAge.setTerapia((String)jComboBoxTerapeuta.getSelectedItem());
//            mod.setNome(jLabelNomePaciente.getText());
//            mod.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
//            controlAge.Salvar(modAge);
//            control.Salvar(mod);
//            preencherTabelaAgendamento("select *from agendamento order by agenda_cod");
//        } catch (SQLException ex) {
//            Logger.getLogger(FormAgendamento.class.getName()).log(Level.SEVERE, null, ex);
//        }                        
    }//GEN-LAST:event_jButtonAdcionarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    public void preencherTabelaPacientes(String Sql){
            
        ArrayList dados = new ArrayList();
        String[] colunas = new String[] {"Cod.", "Nome Paciente", "Fisio", "T.Ocup.", "Fono", "Psic", "Thera", "Music.", "Est.Visual"};
        connBanco.conexao();
        connBanco.executaSQL(Sql);
        try{
            connBanco.rs.first();
            do{
                dados.add(new Object[]{connBanco.rs.getInt("cod_paciente"),connBanco.rs.getString("nome_paciente"),connBanco.rs.getString("fisio_paciente"),connBanco.rs.getString("to_paciente"),connBanco.rs.getString("fono_paciente"),connBanco.rs.getString("psi_paciente"),connBanco.rs.getString("therasuit_paciente"),connBanco.rs.getString("musicoterapia_paciente"),connBanco.rs.getString("estimulacaovisual_paciente")});
                
            }while(connBanco.rs.next());
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayListPac" + ex);
        }
        ModeloTabela modelo= new ModeloTabela(dados, colunas);
        
        jTablePesquisarPaciente.setModel(modelo);
        jTablePesquisarPaciente.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTablePesquisarPaciente.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisarPaciente.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTablePesquisarPaciente.getColumnModel().getColumn(1).setResizable(false);        
        jTablePesquisarPaciente.getColumnModel().getColumn(2).setPreferredWidth(110);
        jTablePesquisarPaciente.getColumnModel().getColumn(2).setResizable(false);
        jTablePesquisarPaciente.getColumnModel().getColumn(3).setPreferredWidth(130);
        jTablePesquisarPaciente.getColumnModel().getColumn(3).setResizable(false);
        jTablePesquisarPaciente.getColumnModel().getColumn(4).setPreferredWidth(110);
        jTablePesquisarPaciente.getColumnModel().getColumn(4).setResizable(false);    
        jTablePesquisarPaciente.getColumnModel().getColumn(5).setPreferredWidth(110);
        jTablePesquisarPaciente.getColumnModel().getColumn(5).setResizable(false);        
        jTablePesquisarPaciente.getColumnModel().getColumn(6).setPreferredWidth(110);
        jTablePesquisarPaciente.getColumnModel().getColumn(6).setResizable(false);        
        jTablePesquisarPaciente.getColumnModel().getColumn(7).setPreferredWidth(110);
        jTablePesquisarPaciente.getColumnModel().getColumn(7).setResizable(false);        
        jTablePesquisarPaciente.getColumnModel().getColumn(8).setPreferredWidth(110);
        jTablePesquisarPaciente.getColumnModel().getColumn(8).setResizable(false);        
        jTablePesquisarPaciente.getColumnModel().getColumn(9).setPreferredWidth(180);
        jTablePesquisarPaciente.getColumnModel().getColumn(9).setResizable(false);               
        jTablePesquisarPaciente.getTableHeader().setReorderingAllowed(false);
        jTablePesquisarPaciente.setAutoResizeMode(jTablePesquisarPaciente.AUTO_RESIZE_OFF);        
        jTablePesquisarPaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        connBanco.desconecta();
        
    }
    
    public void preencherTabelaAgendamento(String Sql){
            
        ArrayList dados = new ArrayList();
        String[] colunas = new String[] {"Cod.", "Nome Paciente", "Terapia", "Dia", "Horário", "Terapeuta"};
        connBanco.conexao();
        connBanco.executaSQL(Sql);
        try{
            connBanco.rs.first();
            do{
                dados.add(new Object[]{connBanco.rs.getInt("cod_paciente"),connBanco.rs.getString("nome_paciente"),connBanco.rs.getString("agenda_terapia"),connBanco.rs.getString("agenda_data"),connBanco.rs.getString("agenda_horario"),connBanco.rs.getString("agenda_terapeuta")});
                
            }while(connBanco.rs.next());
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayListPac" + ex);
        }
        ModeloTabela modelo= new ModeloTabela(dados, colunas);
        
        jTablePesquisarPaciente.setModel(modelo);
        jTablePesquisarPaciente.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTablePesquisarPaciente.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisarPaciente.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTablePesquisarPaciente.getColumnModel().getColumn(1).setResizable(false);        
        jTablePesquisarPaciente.getColumnModel().getColumn(2).setPreferredWidth(110);
        jTablePesquisarPaciente.getColumnModel().getColumn(2).setResizable(false);
        jTablePesquisarPaciente.getColumnModel().getColumn(3).setPreferredWidth(130);
        jTablePesquisarPaciente.getColumnModel().getColumn(3).setResizable(false);
        jTablePesquisarPaciente.getColumnModel().getColumn(4).setPreferredWidth(110);
        jTablePesquisarPaciente.getColumnModel().getColumn(4).setResizable(false);    
        jTablePesquisarPaciente.getColumnModel().getColumn(5).setPreferredWidth(110);
        jTablePesquisarPaciente.getColumnModel().getColumn(5).setResizable(false);                
        jTablePesquisarPaciente.getTableHeader().setReorderingAllowed(false);
        jTablePesquisarPaciente.setAutoResizeMode(jTablePesquisarPaciente.AUTO_RESIZE_OFF);        
        jTablePesquisarPaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        connBanco.desconecta();
        
    }
    
    public void preencherComboTerapeutas(){        
        connBanco.conexao();
        connBanco.executaSQL("select *from funcionarios order by nome_funcionario");
        try {
            connBanco.rs.first();
            jComboBoxTerapeuta.removeAllItems();
            do{     
            jComboBoxTerapeuta.addItem(connBanco.rs.getString("nome_funcionario"));
            connBanco.desconecta();
            }while(connBanco.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher combobox!\nERRO:"+ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdcionar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JComboBox<String> jComboBoxHorario;
    private javax.swing.JComboBox<String> jComboBoxTerapeuta;
    private javax.swing.JComboBox<String> jComboBoxTerapia;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNomePaciente;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableAgendamento;
    private javax.swing.JTable jTablePesquisarPaciente;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
