/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import modeloConection.ConectarNoBanco;
import modeloDao.DaoFuncionarios;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansFuncionarios;
import modeloBeans.ModeloTabela;

/**
 *
 * @author User
 */
public class FormFuncionarios extends javax.swing.JFrame {
    ConectarNoBanco connBanco = new ConectarNoBanco();
    BeansFuncionarios mod = new BeansFuncionarios();
    DaoFuncionarios control = new DaoFuncionarios();
    int flag = 0;
    /**
     * Creates new form FormTerapeutas
     */
    public FormFuncionarios() {
        initComponents();
        preencherTabela("select *from funcionarios order by nome_funcionario");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelNomeTerapeutas = new javax.swing.JLabel();
        jLabelProfissaoTerapeutas = new javax.swing.JLabel();
        jLabelConselhoTerapeutas = new javax.swing.JLabel();
        jLabelRGTerapeutas = new javax.swing.JLabel();
        jLabelCPFTerapeutas = new javax.swing.JLabel();
        jLabelTelefoneTerapeutas = new javax.swing.JLabel();
        jTextFieldNomeFuncionario = new javax.swing.JTextField();
        jTextFieldRgFuncionario = new javax.swing.JTextField();
        jTextFieldConselhoFuncionario = new javax.swing.JTextField();
        jComboBoxProfissaoFuncionario = new javax.swing.JComboBox<>();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelDataNascimento = new javax.swing.JLabel();
        jLabelCod = new javax.swing.JLabel();
        jTextFieldCodFuncionario = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jFormattedTextFieldTelefoneFuncionario = new javax.swing.JFormattedTextField();
        jFormattedTextFieldData_de_Nascimento = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpfFuncionario = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Therapias - Habilitação Pediátrica");
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(null);

        jLabelNomeTerapeutas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeTerapeutas.setText("Nome:");
        getContentPane().add(jLabelNomeTerapeutas);
        jLabelNomeTerapeutas.setBounds(340, 130, 50, 17);

        jLabelProfissaoTerapeutas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProfissaoTerapeutas.setText("Profissão:");
        getContentPane().add(jLabelProfissaoTerapeutas);
        jLabelProfissaoTerapeutas.setBounds(320, 260, 70, 17);

        jLabelConselhoTerapeutas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelConselhoTerapeutas.setText("Conselho:");
        getContentPane().add(jLabelConselhoTerapeutas);
        jLabelConselhoTerapeutas.setBounds(610, 260, 70, 17);

        jLabelRGTerapeutas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRGTerapeutas.setText("RG:");
        getContentPane().add(jLabelRGTerapeutas);
        jLabelRGTerapeutas.setBounds(360, 220, 23, 17);

        jLabelCPFTerapeutas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCPFTerapeutas.setText("CPF:");
        getContentPane().add(jLabelCPFTerapeutas);
        jLabelCPFTerapeutas.setBounds(640, 220, 34, 14);

        jLabelTelefoneTerapeutas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTelefoneTerapeutas.setText("Telefone:");
        getContentPane().add(jLabelTelefoneTerapeutas);
        jLabelTelefoneTerapeutas.setBounds(330, 180, 60, 17);

        jTextFieldNomeFuncionario.setEnabled(false);
        getContentPane().add(jTextFieldNomeFuncionario);
        jTextFieldNomeFuncionario.setBounds(390, 130, 280, 30);

        jTextFieldRgFuncionario.setEnabled(false);
        jTextFieldRgFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRgFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldRgFuncionario);
        jTextFieldRgFuncionario.setBounds(390, 210, 130, 30);

        jTextFieldConselhoFuncionario.setEnabled(false);
        getContentPane().add(jTextFieldConselhoFuncionario);
        jTextFieldConselhoFuncionario.setBounds(680, 250, 130, 30);

        jComboBoxProfissaoFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxProfissaoFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------------------", "Fisio/Therasuit", "T.O./Therasuit", "Fisio/Est. Visual", "T.O./Est.Visual", "Fisioterapia", "Terapia Ocupacional", "Fonoaudiologia", "Psicologia", "Psicopedagogia", "Musicoterapia", "Estimulação Visual", "Administração", "Recepção", "Segurança", "Serviços Gerais", "Auxiliar de Sala", " ", " " }));
        jComboBoxProfissaoFuncionario.setEnabled(false);
        jComboBoxProfissaoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProfissaoFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProfissaoFuncionario);
        jComboBoxProfissaoFuncionario.setBounds(390, 250, 130, 30);

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(60, 190, 100, 30);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(60, 230, 100, 30);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(60, 270, 100, 30);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(60, 310, 100, 30);

        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(60, 420, 100, 30);
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(450, 350, 160, 30);

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(620, 350, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Cadastro de Funcionários");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 20, 470, 44);

        jLabelDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDataNascimento.setText("Data de Nascimento:");
        getContentPane().add(jLabelDataNascimento);
        jLabelDataNascimento.setBounds(540, 180, 140, 17);

        jLabelCod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCod.setText("Cod.:");
        getContentPane().add(jLabelCod);
        jLabelCod.setBounds(690, 140, 34, 17);

        jTextFieldCodFuncionario.setEnabled(false);
        getContentPane().add(jTextFieldCodFuncionario);
        jTextFieldCodFuncionario.setBounds(730, 130, 50, 30);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(60, 350, 100, 30);

        try {
            jFormattedTextFieldTelefoneFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefoneFuncionario.setEnabled(false);
        jFormattedTextFieldTelefoneFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefoneFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldTelefoneFuncionario);
        jFormattedTextFieldTelefoneFuncionario.setBounds(390, 170, 140, 30);

        try {
            jFormattedTextFieldData_de_Nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldData_de_Nascimento.setText("  /  /        ");
        jFormattedTextFieldData_de_Nascimento.setEnabled(false);
        jFormattedTextFieldData_de_Nascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldData_de_NascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldData_de_Nascimento);
        jFormattedTextFieldData_de_Nascimento.setBounds(680, 170, 130, 30);

        try {
            jFormattedTextFieldCpfFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpfFuncionario.setEnabled(false);
        getContentPane().add(jFormattedTextFieldCpfFuncionario);
        jFormattedTextFieldCpfFuncionario.setBounds(680, 210, 120, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/foto.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 20, 180, 150);

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableFuncionarios);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(310, 400, 530, 110);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(280, 320, 670, 5);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_adjacentes.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 980, 550);

        setSize(new java.awt.Dimension(993, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProfissaoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProfissaoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProfissaoFuncionarioActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
        try {
            if(jTextFieldNomeFuncionario.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo NOME para continuar");
                jTextFieldNomeFuncionario.requestFocus();
            }else if(jFormattedTextFieldCpfFuncionario.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo CPF para continuar");
                jFormattedTextFieldCpfFuncionario.requestFocus();
            }else if(jTextFieldConselhoFuncionario.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo CONSELHO para continuar");
                jTextFieldConselhoFuncionario.requestFocus();
            }else if(jTextFieldRgFuncionario.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo RG para continuar");
                jTextFieldRgFuncionario.requestFocus();
            }else if(jFormattedTextFieldData_de_Nascimento.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo DATA DE NASCIMENTO para continuar");
                jFormattedTextFieldData_de_Nascimento.requestFocus();
            }else if(jFormattedTextFieldTelefoneFuncionario.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo TELEFONE para continuar");
                jFormattedTextFieldTelefoneFuncionario.requestFocus();
            }else
                
            if(flag ==1){
            mod.setNome(jTextFieldNomeFuncionario.getText());
            mod.setTelefone(jFormattedTextFieldTelefoneFuncionario.getText());
            mod.setRg(jTextFieldRgFuncionario.getText());
            mod.setCpf(jFormattedTextFieldCpfFuncionario.getText());
            mod.setDatadenascimento(jFormattedTextFieldData_de_Nascimento.getText());
            mod.setProfissao((String) jComboBoxProfissaoFuncionario.getSelectedItem());
            mod.setConselho(jTextFieldConselhoFuncionario.getText());
            control.Salvar(mod);
            jTextFieldNomeFuncionario.setText("");
            jFormattedTextFieldCpfFuncionario.setText("");
            jTextFieldRgFuncionario.setText("");
            jFormattedTextFieldData_de_Nascimento.setText("");
            jFormattedTextFieldTelefoneFuncionario.setText("");
            jComboBoxProfissaoFuncionario.setSelectedItem("");
            jTextFieldConselhoFuncionario.setText("");
            jTextFieldPesquisar.setText("");
            jTextFieldNomeFuncionario.setEnabled(false);
            jFormattedTextFieldTelefoneFuncionario.setEnabled(false);
            jFormattedTextFieldCpfFuncionario.setEnabled(false);
            jTextFieldRgFuncionario.setEnabled(false);
            jFormattedTextFieldData_de_Nascimento.setEnabled(false);
            jTextFieldConselhoFuncionario.setEnabled(false);
            jComboBoxProfissaoFuncionario.setEnabled(false);
            jTextFieldPesquisar.setEnabled(true);
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonPesquisar.setEnabled(true);
            preencherTabela("select *from funcionarios order by nome_funcionario");
            
            }else{
                mod.setCodigo(Integer.parseInt(jTextFieldCodFuncionario.getText()));
                mod.setNome(jTextFieldNomeFuncionario.getText());
                mod.setTelefone(jFormattedTextFieldTelefoneFuncionario.getText());
                mod.setRg(jTextFieldRgFuncionario.getText());
                mod.setCpf(jFormattedTextFieldCpfFuncionario.getText());
                mod.setDatadenascimento(jFormattedTextFieldData_de_Nascimento.getText());
                mod.setProfissao((String) jComboBoxProfissaoFuncionario.getSelectedItem());
                mod.setConselho(jTextFieldConselhoFuncionario.getText());
                control.Editar(mod);
                jTextFieldCodFuncionario.setText("");
                jTextFieldNomeFuncionario.setText("");
                jFormattedTextFieldTelefoneFuncionario.setText("");
                jTextFieldRgFuncionario.setText("");
                jTextFieldPesquisar.setText("");
                jFormattedTextFieldCpfFuncionario.setText("");
                jFormattedTextFieldData_de_Nascimento.setText("");
                jComboBoxProfissaoFuncionario.setSelectedItem("");
                jTextFieldConselhoFuncionario.setText("");
                jTextFieldNomeFuncionario.setEnabled(false);
                jFormattedTextFieldTelefoneFuncionario.setEnabled(false);
                jFormattedTextFieldCpfFuncionario.setEnabled(false);
                jTextFieldRgFuncionario.setEnabled(false);
                jFormattedTextFieldData_de_Nascimento.setEnabled(false);
                jTextFieldConselhoFuncionario.setEnabled(false);
                jComboBoxProfissaoFuncionario.setEnabled(false);
                jTextFieldPesquisar.setEnabled(true);
                jButtonPesquisar.setEnabled(true);
                jButtonSalvar.setEnabled(false);
                jButtonNovo.setEnabled(true);
                jButtonCancelar.setEnabled(false);
                preencherTabela("select *from funcionarios order by nome_funcionario");
            }
        } catch (SQLException ex) {
            //Logger.getLogger(FormFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNomeFuncionario.setEnabled(true);
        jFormattedTextFieldTelefoneFuncionario.setEnabled(true);
        jFormattedTextFieldCpfFuncionario.setEnabled(true);
        jTextFieldRgFuncionario.setEnabled(true);
        jFormattedTextFieldData_de_Nascimento.setEnabled(true);
        jTextFieldConselhoFuncionario.setEnabled(true);
        jTextFieldPesquisar.setEnabled(false);
        jComboBoxProfissaoFuncionario.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldNomeFuncionario.setText("");
        jFormattedTextFieldCpfFuncionario.setText("");
        jTextFieldRgFuncionario.setText("");
        jFormattedTextFieldData_de_Nascimento.setText("");
        jFormattedTextFieldTelefoneFuncionario.setText("");
        jComboBoxProfissaoFuncionario.setSelectedItem("");
        jTextFieldConselhoFuncionario.setText("");
        jTextFieldPesquisar.setText("");
        jTextFieldCodFuncionario.setText("");
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldPesquisar.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisar(jTextFieldPesquisar.getText());
        BeansFuncionarios model = control.buscaFuncionarios(mod);
        jTextFieldNomeFuncionario.setText(model.getNome());  
        jTextFieldCodFuncionario.setText(String.valueOf(model.getCodigo()));
        jFormattedTextFieldTelefoneFuncionario.setText(model.getTelefone());
        jTextFieldRgFuncionario.setText(model.getRg());
        jFormattedTextFieldCpfFuncionario.setText(model.getCpf());
        jFormattedTextFieldData_de_Nascimento.setText(model.getDatadenascimento());
        jComboBoxProfissaoFuncionario.setSelectedItem(model.getProfissao());
        jTextFieldConselhoFuncionario.setText(model.getConselho());
        preencherTabela("select *from funcionarios where nome_funcionario like'%" + jTextFieldPesquisar.getText() +"%'");
        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNomeFuncionario.setEnabled(!true);
        jFormattedTextFieldTelefoneFuncionario.setEnabled(!true);
        jFormattedTextFieldCpfFuncionario.setEnabled(!true);
        jTextFieldRgFuncionario.setEnabled(!true);
        jFormattedTextFieldData_de_Nascimento.setEnabled(!true);
        jTextFieldConselhoFuncionario.setEnabled(!true);
        jTextFieldPesquisar.setEnabled(true);
        jComboBoxProfissaoFuncionario.setEnabled(!true);
        jButtonPesquisar.setEnabled(true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldNomeFuncionario.setText("");
        jFormattedTextFieldCpfFuncionario.setText("");
        jTextFieldRgFuncionario.setText("");
        jFormattedTextFieldData_de_Nascimento.setText("");
        jFormattedTextFieldTelefoneFuncionario.setText("");
        jComboBoxProfissaoFuncionario.setSelectedItem("");
        jTextFieldConselhoFuncionario.setText("");
        jTextFieldPesquisar.setText("");
        jTextFieldCodFuncionario.setText("");
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNomeFuncionario.setEnabled(true);
        jFormattedTextFieldTelefoneFuncionario.setEnabled(true);
        jFormattedTextFieldCpfFuncionario.setEnabled(true);
        jTextFieldRgFuncionario.setEnabled(true);
        jFormattedTextFieldData_de_Nascimento.setEnabled(true);
        jComboBoxProfissaoFuncionario.setEnabled(true);
        jTextFieldConselhoFuncionario.setEnabled(true);
        jTextFieldPesquisar.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTabela("select *from funcionarios");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
       int resposta= 0;
       resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
       if(resposta == JOptionPane.YES_OPTION){
            mod.setCodigo(Integer.parseInt(jTextFieldCodFuncionario.getText()));
            control.Excluir(mod);
            jTextFieldCodFuncionario.setText("");
            jTextFieldNomeFuncionario.setText("");
            jFormattedTextFieldCpfFuncionario.setText("");
            jTextFieldRgFuncionario.setText("");
            jFormattedTextFieldData_de_Nascimento.setText("");
            jFormattedTextFieldTelefoneFuncionario.setText("");
            jComboBoxProfissaoFuncionario.setSelectedItem("");
            jTextFieldConselhoFuncionario.setText("");
            jTextFieldPesquisar.setText("");
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonExcluir.setEnabled(false);  
            preencherTabela("select *from funcionarios order by nome_funcionario");
       }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[] {"Cód.", "Nome", "Telefone", "Profissão", "Conselho", "CPF", "RG", "Data de Nascimento"};
        connBanco.conexao();
        connBanco.executaSQL(Sql);
        try{
            connBanco.rs.first();
            do{
                dados.add(new Object[]{connBanco.rs.getInt("cod_funcionario"), connBanco.rs.getString("nome_funcionario"), connBanco.rs.getString("telefone_funcionario"), connBanco.rs.getString("profissao"), connBanco.rs.getString("conselho"), connBanco.rs.getString("cpf_funcionario"), connBanco.rs.getString("rg_funcionario"), connBanco.rs.getString("data_de_nascimento")});
                
            }while(connBanco.rs.next());
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Buscar novo funcionário");
        }
        ModeloTabela modelo= new ModeloTabela(dados, colunas);
        
        jTableFuncionarios.setModel(modelo);
        jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableFuncionarios.getColumnModel().getColumn(0).setResizable(false);
        jTableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTableFuncionarios.getColumnModel().getColumn(1).setResizable(false);        
        jTableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableFuncionarios.getColumnModel().getColumn(2).setResizable(false);        
        jTableFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTableFuncionarios.getColumnModel().getColumn(3).setResizable(false);        
        jTableFuncionarios.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableFuncionarios.getColumnModel().getColumn(4).setResizable(false);        
        jTableFuncionarios.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTableFuncionarios.getColumnModel().getColumn(5).setResizable(false);        
        jTableFuncionarios.getColumnModel().getColumn(6).setPreferredWidth(130);
        jTableFuncionarios.getColumnModel().getColumn(6).setResizable(false);        
        jTableFuncionarios.getColumnModel().getColumn(7).setPreferredWidth(130);
        jTableFuncionarios.getColumnModel().getColumn(7).setResizable(false);  
        jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
        jTableFuncionarios.setAutoResizeMode(jTableFuncionarios.AUTO_RESIZE_OFF);
        jTableFuncionarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        connBanco.desconecta();
        
    }
   
    
    private void jFormattedTextFieldTelefoneFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneFuncionarioActionPerformed

    }//GEN-LAST:event_jFormattedTextFieldTelefoneFuncionarioActionPerformed

    private void jTextFieldRgFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRgFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRgFuncionarioActionPerformed

    private void jFormattedTextFieldData_de_NascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldData_de_NascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldData_de_NascimentoActionPerformed

    private void jTableFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionariosMouseClicked
        String nome_funcionario = "" + jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 1);
        connBanco.conexao();
        connBanco.executaSQL("select * from funcionarios where nome_funcionario='"+nome_funcionario+"'");
        try {
            connBanco.rs.first();
            jTextFieldCodFuncionario.setText(String.valueOf(connBanco.rs.getInt("cod_funcionario")));
            jTextFieldNomeFuncionario.setText(connBanco.rs.getString("nome_funcionario")); 
            jFormattedTextFieldTelefoneFuncionario.setText(connBanco.rs.getString("telefone_funcionario"));
            jTextFieldRgFuncionario.setText(connBanco.rs.getString("rg_funcionario"));
            jFormattedTextFieldCpfFuncionario.setText(connBanco.rs.getString("cpf_funcionario"));
            jFormattedTextFieldData_de_Nascimento.setText(connBanco.rs.getString("data_de_nascimento"));        
            jTextFieldConselhoFuncionario.setText(connBanco.rs.getString("conselho"));
            jComboBoxProfissaoFuncionario.setSelectedItem(connBanco.rs.getString("profissao"));
            connBanco.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar os dados!\nERRO:" + ex);
        }
        connBanco.desconecta();
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        
    }//GEN-LAST:event_jTableFuncionariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxProfissaoFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfFuncionario;
    private javax.swing.JFormattedTextField jFormattedTextFieldData_de_Nascimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefoneFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCPFTerapeutas;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelConselhoTerapeutas;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelNomeTerapeutas;
    private javax.swing.JLabel jLabelProfissaoTerapeutas;
    private javax.swing.JLabel jLabelRGTerapeutas;
    private javax.swing.JLabel jLabelTelefoneTerapeutas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextFieldCodFuncionario;
    private javax.swing.JTextField jTextFieldConselhoFuncionario;
    private javax.swing.JTextField jTextFieldNomeFuncionario;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldRgFuncionario;
    // End of variables declaration//GEN-END:variables
}
