/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansPacientes;
import modeloBeans.ModeloTabela;
import modeloConection.ConectarNoBanco;
import modeloDao.DaoPacientes;


/**
 *
 * @author User
 */
public class FormPacientes extends javax.swing.JFrame {
    ConectarNoBanco connBanco = new ConectarNoBanco();
    BeansPacientes mod = new BeansPacientes();
    DaoPacientes control = new DaoPacientes();
    int flag = 0;

    /**
     * Creates new form FormPacientes
     */
    public FormPacientes() {
        initComponents();
        preencherTabelaPacientes("select *from pacientes order by nome_paciente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelEndereço_paciente = new javax.swing.JLabel();
        jLabelNome_Filiaçao1 = new javax.swing.JLabel();
        jLabelNome_Filiaçao2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelParentesco_filiaçao1 = new javax.swing.JLabel();
        jLabelParentesco_filiaçao2 = new javax.swing.JLabel();
        jLabelTel_Filiaçao1 = new javax.swing.JLabel();
        jLabelTel_paciente = new javax.swing.JLabel();
        jLabelCpf_paciente = new javax.swing.JLabel();
        jLabelTel_Filiaçao2 = new javax.swing.JLabel();
        jLabelRg_paciente = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelDadosPaciente = new javax.swing.JLabel();
        jTextFieldCodPaciente = new javax.swing.JTextField();
        jTextFieldNomePaciente = new javax.swing.JTextField();
        jTextFieldEndereçoPaciente = new javax.swing.JTextField();
        jFormattedTextFieldTelefonePaciente = new javax.swing.JFormattedTextField();
        jTextFieldNome_Filiaçao1 = new javax.swing.JTextField();
        jTextFieldNome_Filiaçao2 = new javax.swing.JTextField();
        jFormattedTextFieldTel_Filiaçao1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTel_filiaçao2 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpf_paciente = new javax.swing.JFormattedTextField();
        jTextFieldRg_paciente = new javax.swing.JTextField();
        jComboBoxDadosPaciente = new javax.swing.JComboBox<>();
        jFormattedTextFieldData_de_nascimento_paciente = new javax.swing.JFormattedTextField();
        jLabelComplemento_paciente = new javax.swing.JLabel();
        jLabelBairroPaciente = new javax.swing.JLabel();
        jTextFieldComplementoPaciente = new javax.swing.JTextField();
        jTextFieldBairroPaciente = new javax.swing.JTextField();
        jComboBoxParentesco_filiaçao1 = new javax.swing.JComboBox<>();
        jComboBoxParentesco_filiaçao2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabelCidade_paciente = new javax.swing.JLabel();
        jLabelEstado_paciente = new javax.swing.JLabel();
        jTextFieldCidade_paciente = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jComboBoxFisioterapia = new javax.swing.JComboBox<>();
        jComboBoxTerapiaOcupacional = new javax.swing.JComboBox<>();
        jComboBoxFonoaudiologia = new javax.swing.JComboBox<>();
        jComboBoxPsicologia = new javax.swing.JComboBox<>();
        jComboBoxTherasuit = new javax.swing.JComboBox<>();
        jComboBoxMusicoterapia = new javax.swing.JComboBox<>();
        jComboBoxEstimulacaoVisual = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Therapias - Habilitação Pediátrica");
        getContentPane().setLayout(null);

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(60, 250, 100, 30);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(60, 290, 100, 30);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(60, 330, 100, 30);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(60, 370, 100, 30);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(60, 410, 100, 30);

        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(60, 480, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Cadastro de Pacientes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 10, 370, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Nome paciente:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 140, 100, 16);

        jLabelEndereço_paciente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEndereço_paciente.setText("Endereço:");
        getContentPane().add(jLabelEndereço_paciente);
        jLabelEndereço_paciente.setBounds(380, 450, 60, 16);

        jLabelNome_Filiaçao1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNome_Filiaçao1.setText("Filiação 1:");
        getContentPane().add(jLabelNome_Filiaçao1);
        jLabelNome_Filiaçao1.setBounds(360, 260, 70, 16);

        jLabelNome_Filiaçao2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelNome_Filiaçao2.setText("Filiação 2:");
        getContentPane().add(jLabelNome_Filiaçao2);
        jLabelNome_Filiaçao2.setBounds(360, 300, 80, 16);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Data de nascimento: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 180, 130, 16);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Cod.:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 100, 31, 16);

        jLabelParentesco_filiaçao1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelParentesco_filiaçao1.setText("Parentesco:");
        getContentPane().add(jLabelParentesco_filiaçao1);
        jLabelParentesco_filiaçao1.setBounds(890, 260, 70, 16);

        jLabelParentesco_filiaçao2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelParentesco_filiaçao2.setText("Parentesco:");
        getContentPane().add(jLabelParentesco_filiaçao2);
        jLabelParentesco_filiaçao2.setBounds(890, 300, 70, 16);

        jLabelTel_Filiaçao1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelTel_Filiaçao1.setText("Telefone:");
        getContentPane().add(jLabelTel_Filiaçao1);
        jLabelTel_Filiaçao1.setBounds(650, 260, 55, 16);

        jLabelTel_paciente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelTel_paciente.setText("Telefone:");
        getContentPane().add(jLabelTel_paciente);
        jLabelTel_paciente.setBounds(700, 400, 60, 16);

        jLabelCpf_paciente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelCpf_paciente.setText("CPF: ");
        getContentPane().add(jLabelCpf_paciente);
        jLabelCpf_paciente.setBounds(410, 400, 40, 16);

        jLabelTel_Filiaçao2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelTel_Filiaçao2.setText("Telefone:");
        getContentPane().add(jLabelTel_Filiaçao2);
        jLabelTel_Filiaçao2.setBounds(650, 300, 60, 16);

        jLabelRg_paciente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelRg_paciente.setText("RG:");
        getContentPane().add(jLabelRg_paciente);
        jLabelRg_paciente.setBounds(540, 400, 40, 16);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Dados para Relatórios:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(280, 360, 210, 20);

        jLabelDadosPaciente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelDadosPaciente.setText("Dados:");
        getContentPane().add(jLabelDadosPaciente);
        jLabelDadosPaciente.setBounds(280, 400, 40, 16);

        jTextFieldCodPaciente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextFieldCodPaciente.setEnabled(false);
        getContentPane().add(jTextFieldCodPaciente);
        jTextFieldCodPaciente.setBounds(450, 90, 60, 30);

        jTextFieldNomePaciente.setEnabled(false);
        getContentPane().add(jTextFieldNomePaciente);
        jTextFieldNomePaciente.setBounds(450, 130, 280, 30);

        jTextFieldEndereçoPaciente.setEnabled(false);
        getContentPane().add(jTextFieldEndereçoPaciente);
        jTextFieldEndereçoPaciente.setBounds(450, 440, 310, 30);

        try {
            jFormattedTextFieldTelefonePaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefonePaciente.setEnabled(false);
        getContentPane().add(jFormattedTextFieldTelefonePaciente);
        jFormattedTextFieldTelefonePaciente.setBounds(760, 390, 120, 30);

        jTextFieldNome_Filiaçao1.setEnabled(false);
        getContentPane().add(jTextFieldNome_Filiaçao1);
        jTextFieldNome_Filiaçao1.setBounds(430, 250, 200, 30);

        jTextFieldNome_Filiaçao2.setEnabled(false);
        getContentPane().add(jTextFieldNome_Filiaçao2);
        jTextFieldNome_Filiaçao2.setBounds(430, 290, 200, 30);

        try {
            jFormattedTextFieldTel_Filiaçao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTel_Filiaçao1.setEnabled(false);
        getContentPane().add(jFormattedTextFieldTel_Filiaçao1);
        jFormattedTextFieldTel_Filiaçao1.setBounds(720, 250, 150, 30);

        try {
            jFormattedTextFieldTel_filiaçao2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTel_filiaçao2.setEnabled(false);
        getContentPane().add(jFormattedTextFieldTel_filiaçao2);
        jFormattedTextFieldTel_filiaçao2.setBounds(720, 290, 150, 30);

        try {
            jFormattedTextFieldCpf_paciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpf_paciente.setEnabled(false);
        jFormattedTextFieldCpf_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCpf_pacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldCpf_paciente);
        jFormattedTextFieldCpf_paciente.setBounds(440, 390, 90, 30);

        jTextFieldRg_paciente.setEnabled(false);
        getContentPane().add(jTextFieldRg_paciente);
        jTextFieldRg_paciente.setBounds(570, 390, 120, 30);

        jComboBoxDadosPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------", "Filiação 1", "Filiação 2", "Paciente" }));
        jComboBoxDadosPaciente.setEnabled(false);
        getContentPane().add(jComboBoxDadosPaciente);
        jComboBoxDadosPaciente.setBounds(280, 420, 90, 30);

        try {
            jFormattedTextFieldData_de_nascimento_paciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldData_de_nascimento_paciente.setEnabled(false);
        jFormattedTextFieldData_de_nascimento_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldData_de_nascimento_pacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldData_de_nascimento_paciente);
        jFormattedTextFieldData_de_nascimento_paciente.setBounds(450, 170, 140, 30);

        jLabelComplemento_paciente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelComplemento_paciente.setText("Complemento:");
        getContentPane().add(jLabelComplemento_paciente);
        jLabelComplemento_paciente.setBounds(780, 450, 90, 16);

        jLabelBairroPaciente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelBairroPaciente.setText("Bairro:");
        getContentPane().add(jLabelBairroPaciente);
        jLabelBairroPaciente.setBounds(1000, 450, 39, 16);

        jTextFieldComplementoPaciente.setEnabled(false);
        getContentPane().add(jTextFieldComplementoPaciente);
        jTextFieldComplementoPaciente.setBounds(870, 440, 120, 30);

        jTextFieldBairroPaciente.setEnabled(false);
        getContentPane().add(jTextFieldBairroPaciente);
        jTextFieldBairroPaciente.setBounds(1050, 440, 110, 30);

        jComboBoxParentesco_filiaçao1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------", "Pai", "Mãe", "Avó", "Avô", "Padastro", "Madastra", "Tio", "Tia", " " }));
        jComboBoxParentesco_filiaçao1.setEnabled(false);
        getContentPane().add(jComboBoxParentesco_filiaçao1);
        jComboBoxParentesco_filiaçao1.setBounds(960, 250, 110, 30);

        jComboBoxParentesco_filiaçao2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------", "Pai", "Mãe", "Avó", "Avô", "Padastro", "Madastra", "Tio", "Tia" }));
        jComboBoxParentesco_filiaçao2.setEnabled(false);
        getContentPane().add(jComboBoxParentesco_filiaçao2);
        jComboBoxParentesco_filiaçao2.setBounds(960, 290, 110, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/foto.png"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 225));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 80, 180, 140);

        jLabelCidade_paciente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelCidade_paciente.setText("Cidade:");
        getContentPane().add(jLabelCidade_paciente);
        jLabelCidade_paciente.setBounds(890, 400, 50, 16);

        jLabelEstado_paciente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelEstado_paciente.setText("Estado:");
        getContentPane().add(jLabelEstado_paciente);
        jLabelEstado_paciente.setBounds(1060, 400, 50, 16);

        jTextFieldCidade_paciente.setEnabled(false);
        getContentPane().add(jTextFieldCidade_paciente);
        jTextFieldCidade_paciente.setBounds(940, 390, 110, 30);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------", "AC", "AL", "AP", "AM", "BA ", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", "DF" }));
        jComboBoxEstado.setEnabled(false);
        getContentPane().add(jComboBoxEstado);
        jComboBoxEstado.setBounds(1110, 390, 60, 30);

        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(630, 510, 220, 30);

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(860, 510, 90, 30);

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePacientes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(430, 550, 660, 110);

        jComboBoxFisioterapia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "1 x", "2 x", "3 x", "4 x", "5 x", "6 x", "7 x", "8 x", "9 x", "10 x", " " }));
        jComboBoxFisioterapia.setEnabled(false);
        getContentPane().add(jComboBoxFisioterapia);
        jComboBoxFisioterapia.setBounds(906, 80, 60, 20);

        jComboBoxTerapiaOcupacional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "1 x", "2 x", "3 x", "4 x", "5 x", "6 x", "7 x", "8 x", "9 x", "10 x", " " }));
        jComboBoxTerapiaOcupacional.setEnabled(false);
        getContentPane().add(jComboBoxTerapiaOcupacional);
        jComboBoxTerapiaOcupacional.setBounds(906, 110, 60, 20);

        jComboBoxFonoaudiologia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "1 x", "2 x", "3 x", "4 x", "5 x", "6 x", "7 x", "8 x", "9 x", "10 x", " " }));
        jComboBoxFonoaudiologia.setEnabled(false);
        getContentPane().add(jComboBoxFonoaudiologia);
        jComboBoxFonoaudiologia.setBounds(906, 140, 60, 20);

        jComboBoxPsicologia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "1 x", "2 x", "3 x", "4 x", "5 x", "6 x", "7 x", "8 x", "9 x", "10 x", " " }));
        jComboBoxPsicologia.setEnabled(false);
        getContentPane().add(jComboBoxPsicologia);
        jComboBoxPsicologia.setBounds(906, 170, 60, 20);

        jComboBoxTherasuit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "1 x", "2 x", "3 x", "4 x", "5 x", "6 x", "7 x", "8 x", "9 x", "10 x", " " }));
        jComboBoxTherasuit.setEnabled(false);
        getContentPane().add(jComboBoxTherasuit);
        jComboBoxTherasuit.setBounds(1106, 80, 60, 20);

        jComboBoxMusicoterapia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "1 x", "2 x", "3 x", "4 x", "5 x", "6 x", "7 x", "8 x", "9 x", "10 x", " " }));
        jComboBoxMusicoterapia.setEnabled(false);
        getContentPane().add(jComboBoxMusicoterapia);
        jComboBoxMusicoterapia.setBounds(1106, 110, 60, 20);

        jComboBoxEstimulacaoVisual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "1 x", "2 x", "3 x", "4 x", "5 x", "6 x", "7 x", "8 x", "9 x", "10 x", " " }));
        jComboBoxEstimulacaoVisual.setEnabled(false);
        getContentPane().add(jComboBoxEstimulacaoVisual);
        jComboBoxEstimulacaoVisual.setBounds(1106, 140, 60, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Fisioterapia:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(830, 80, 80, 16);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Terapia Ocupacional:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(780, 110, 130, 16);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Fonoaudiologia:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(810, 140, 91, 16);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Psicologia:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(840, 170, 61, 16);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Therasuit:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1030, 80, 70, 16);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setText("Musicoterapia:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1010, 110, 84, 16);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setText("Estimulação Visual:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(980, 140, 111, 16);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.add(jPanel5);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(280, 220, 910, 5);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(280, 340, 910, 5);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jPanel6);
        jPanel6.setBounds(280, 490, 910, 5);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_adjacentes.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 1210, 670);

        setSize(new java.awt.Dimension(1225, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldData_de_nascimento_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldData_de_nascimento_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldData_de_nascimento_pacienteActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldCodPaciente.setText("");
        jTextFieldNomePaciente.setText("");
        jFormattedTextFieldCpf_paciente.setText("");
        jTextFieldRg_paciente.setText("");
        jFormattedTextFieldData_de_nascimento_paciente.setText("");
        jFormattedTextFieldTelefonePaciente.setText("");
        jComboBoxParentesco_filiaçao1.setSelectedItem("");
        jComboBoxParentesco_filiaçao2.setSelectedItem("");
        jComboBoxDadosPaciente.setSelectedItem("");
        jFormattedTextFieldTel_Filiaçao1.setText("");
        jFormattedTextFieldTel_filiaçao2.setText("");
        jTextFieldNome_Filiaçao1.setText("");
        jTextFieldNome_Filiaçao2.setText("");
        jComboBoxParentesco_filiaçao1.setSelectedItem("");
        jComboBoxParentesco_filiaçao2.setSelectedItem("");
        jTextFieldEndereçoPaciente.setText("");
        jTextFieldCidade_paciente.setText("");
        jComboBoxEstado.setSelectedItem("");        
        jTextFieldComplementoPaciente.setText("");
        jTextFieldBairroPaciente.setText("");
        jComboBoxFisioterapia.setSelectedItem("");
        jComboBoxTerapiaOcupacional.setSelectedItem("");
        jComboBoxFonoaudiologia.setSelectedItem("");
        jComboBoxPsicologia.setSelectedItem("");
        jComboBoxTherasuit.setSelectedItem("");
        jComboBoxMusicoterapia.setSelectedItem("");
        jComboBoxEstimulacaoVisual.setSelectedItem("");
        jTextFieldNomePaciente.setEnabled(true);
        jFormattedTextFieldCpf_paciente.setEnabled(true);
        jTextFieldRg_paciente.setEnabled(true);
        jFormattedTextFieldData_de_nascimento_paciente.setEnabled(true);
        jFormattedTextFieldTelefonePaciente.setEnabled(true);
        jComboBoxParentesco_filiaçao1.setEnabled(true);
        jComboBoxParentesco_filiaçao2.setEnabled(true);
        jComboBoxDadosPaciente.setEnabled(true);
        jFormattedTextFieldTel_Filiaçao1.setEnabled(true);
        jFormattedTextFieldTel_filiaçao2.setEnabled(true);
        jTextFieldNome_Filiaçao1.setEnabled(true);
        jTextFieldNome_Filiaçao2.setEnabled(true);
        jTextFieldEndereçoPaciente.setEnabled(true);
        jTextFieldComplementoPaciente.setEnabled(true);
        jTextFieldBairroPaciente.setEnabled(true);
        jTextFieldCidade_paciente.setEnabled(true);
        jComboBoxEstado.setEnabled(true);        
        jComboBoxFisioterapia.setEnabled(true);
        jComboBoxTerapiaOcupacional.setEnabled(true);
        jComboBoxFonoaudiologia.setEnabled(true);
        jComboBoxPsicologia.setEnabled(true);
        jComboBoxTherasuit.setEnabled(true);
        jComboBoxMusicoterapia.setEnabled(true);
        jComboBoxEstimulacaoVisual.setEnabled(true);        
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            if(jTextFieldNomePaciente.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo NOME PACIENTE para continuar");
                jTextFieldNomePaciente.requestFocus();
            }else if(jFormattedTextFieldData_de_nascimento_paciente.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo DATA DE NASCIMENTO para continuar");
                jFormattedTextFieldData_de_nascimento_paciente.requestFocus();
            }else if(jFormattedTextFieldCpf_paciente.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo CPF para continuar");
                jFormattedTextFieldCpf_paciente.requestFocus();
            }else if(jTextFieldRg_paciente.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha o campo RG para continuar");
                jTextFieldRg_paciente.requestFocus();
            }else
            
            if(flag ==1){
            mod.setNome(jTextFieldNomePaciente.getText());
            mod.setDatadenascimento(jFormattedTextFieldData_de_nascimento_paciente.getText());
            mod.setQntdFisio((String)jComboBoxFisioterapia.getSelectedItem());
            mod.setQntdTO((String)jComboBoxTerapiaOcupacional.getSelectedItem());
            mod.setQntdFono((String)jComboBoxFonoaudiologia.getSelectedItem());
            mod.setQntdPsi((String)jComboBoxPsicologia.getSelectedItem());
            mod.setQntdTherasuit((String)jComboBoxTherasuit.getSelectedItem());
            mod.setQntdMusicoterapia((String)jComboBoxMusicoterapia.getSelectedItem());
            mod.setQntdEstVisual((String)jComboBoxEstimulacaoVisual.getSelectedItem());
            mod.setFiliacao_1(jTextFieldNome_Filiaçao1.getText());
            mod.setTel_fil_1(jFormattedTextFieldTel_Filiaçao1.getText());
            mod.setParentesco_1((String)jComboBoxParentesco_filiaçao1.getSelectedItem());            
            mod.setFiliacao_2(jTextFieldNome_Filiaçao2.getText());            
            mod.setTel_fil_2(jFormattedTextFieldTel_filiaçao2.getText());            
            mod.setParentesco_2((String)jComboBoxParentesco_filiaçao2.getSelectedItem());          
            mod.setDados((String)jComboBoxDadosPaciente.getSelectedItem());   
            mod.setCpf(jFormattedTextFieldCpf_paciente.getText());
            mod.setRg(jTextFieldRg_paciente.getText());
            mod.setTelefone(jFormattedTextFieldTelefonePaciente.getText());
            mod.setEndereço(jTextFieldEndereçoPaciente.getText());   
            mod.setComplemento(jTextFieldComplementoPaciente.getText());   
            mod.setBairro(jTextFieldBairroPaciente.getText()); 
            mod.setCidade(jTextFieldCidade_paciente.getText()); 
            mod.setEstado((String)jComboBoxEstado.getSelectedItem()); 
            control.Salvar(mod);
            jTextFieldNomePaciente.setText("");
            jFormattedTextFieldCpf_paciente.setText("");
            jTextFieldRg_paciente.setText("");
            jFormattedTextFieldData_de_nascimento_paciente.setText("");
            jFormattedTextFieldTelefonePaciente.setText("");
            jComboBoxParentesco_filiaçao1.setSelectedItem("");
            jComboBoxParentesco_filiaçao2.setSelectedItem("");
            jComboBoxDadosPaciente.setSelectedItem("");
            jFormattedTextFieldTel_Filiaçao1.setText("");
            jFormattedTextFieldTel_filiaçao2.setText("");
            jTextFieldNome_Filiaçao1.setText("");
            jTextFieldNome_Filiaçao2.setText("");
            jTextFieldEndereçoPaciente.setText("");
            jTextFieldComplementoPaciente.setText("");
            jTextFieldBairroPaciente.setText("");
            jTextFieldCidade_paciente.setText("");
            jComboBoxEstado.setSelectedItem("");
            jComboBoxFisioterapia.setSelectedItem("");
            jComboBoxTerapiaOcupacional.setSelectedItem("");
            jComboBoxFonoaudiologia.setSelectedItem("");
            jComboBoxPsicologia.setSelectedItem("");
            jComboBoxTherasuit.setSelectedItem("");
            jComboBoxMusicoterapia.setSelectedItem("");
            jComboBoxEstimulacaoVisual.setSelectedItem("");
            jTextFieldNomePaciente.setEnabled(false);
            jFormattedTextFieldCpf_paciente.setEnabled(false);
            jTextFieldRg_paciente.setEnabled(false);
            jFormattedTextFieldData_de_nascimento_paciente.setEnabled(false);
            jFormattedTextFieldTelefonePaciente.setEnabled(false);
            jComboBoxParentesco_filiaçao1.setEnabled(false);
            jComboBoxParentesco_filiaçao2.setEnabled(false);
            jComboBoxDadosPaciente.setEnabled(false);
            jFormattedTextFieldTel_Filiaçao1.setEnabled(false);
            jFormattedTextFieldTel_filiaçao2.setEnabled(false);
            jTextFieldNome_Filiaçao1.setEnabled(false);
            jTextFieldNome_Filiaçao2.setEnabled(false);
            jTextFieldEndereçoPaciente.setEnabled(false);
            jTextFieldComplementoPaciente.setEnabled(false);
            jTextFieldBairroPaciente.setEnabled(false);
            jTextFieldCidade_paciente.setEnabled(false);
            jComboBoxEstado.setEnabled(false);            
            jComboBoxFisioterapia.setEnabled(false);
            jComboBoxTerapiaOcupacional.setEnabled(false);
            jComboBoxFonoaudiologia.setEnabled(false);
            jComboBoxPsicologia.setEnabled(false);
            jComboBoxTherasuit.setEnabled(false);
            jComboBoxMusicoterapia.setEnabled(false);
            jComboBoxEstimulacaoVisual.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            preencherTabelaPacientes("select *from pacientes order by nome_paciente");
            }else{
                mod.setCodigo(Integer.parseInt(jTextFieldCodPaciente.getText()));
                mod.setNome(jTextFieldNomePaciente.getText());
                mod.setDatadenascimento(jFormattedTextFieldData_de_nascimento_paciente.getText());
                mod.setQntdFisio((String)jComboBoxFisioterapia.getSelectedItem());
                mod.setQntdTO((String)jComboBoxTerapiaOcupacional.getSelectedItem());
                mod.setQntdFono((String)jComboBoxFonoaudiologia.getSelectedItem());
                mod.setQntdPsi((String)jComboBoxPsicologia.getSelectedItem());
                mod.setQntdTherasuit((String)jComboBoxTherasuit.getSelectedItem());
                mod.setQntdMusicoterapia((String)jComboBoxMusicoterapia.getSelectedItem());
                mod.setQntdEstVisual((String)jComboBoxEstimulacaoVisual.getSelectedItem());
                mod.setFiliacao_1(jTextFieldNome_Filiaçao1.getText());
                mod.setTel_fil_1(jFormattedTextFieldTel_Filiaçao1.getText());
                mod.setParentesco_1((String)jComboBoxParentesco_filiaçao1.getSelectedItem());            
                mod.setFiliacao_2(jTextFieldNome_Filiaçao2.getText());            
                mod.setTel_fil_2(jFormattedTextFieldTel_filiaçao2.getText());            
                mod.setParentesco_2((String)jComboBoxParentesco_filiaçao2.getSelectedItem());          
                mod.setDados((String)jComboBoxDadosPaciente.getSelectedItem());   
                mod.setCpf(jFormattedTextFieldCpf_paciente.getText());
                mod.setRg(jTextFieldRg_paciente.getText());
                mod.setTelefone(jFormattedTextFieldTelefonePaciente.getText());
                mod.setEndereço(jTextFieldEndereçoPaciente.getText());   
                mod.setComplemento(jTextFieldComplementoPaciente.getText());   
                mod.setBairro(jTextFieldBairroPaciente.getText());   
                mod.setCidade(jTextFieldCidade_paciente.getText());                   
                mod.setEstado((String)jComboBoxEstado.getSelectedItem());                   
                control.Editar(mod);
                jTextFieldNomePaciente.setText("");
                jFormattedTextFieldCpf_paciente.setText("");
                jTextFieldRg_paciente.setText("");
                jFormattedTextFieldData_de_nascimento_paciente.setText("");
                jFormattedTextFieldTelefonePaciente.setText("");
                jComboBoxParentesco_filiaçao1.setSelectedItem("");
                jComboBoxParentesco_filiaçao2.setSelectedItem("");
                jComboBoxDadosPaciente.setSelectedItem("");
                jFormattedTextFieldTel_Filiaçao1.setText("");
                jFormattedTextFieldTel_filiaçao2.setText("");
                jTextFieldNome_Filiaçao1.setText("");
                jTextFieldNome_Filiaçao2.setText("");
                jTextFieldEndereçoPaciente.setText("");
                jTextFieldComplementoPaciente.setText("");
                jTextFieldBairroPaciente.setText("");
                jTextFieldCidade_paciente.setText("");
                jComboBoxEstado.setSelectedItem("");
                jComboBoxFisioterapia.setSelectedItem("");
                jComboBoxTerapiaOcupacional.setSelectedItem("");
                jComboBoxFonoaudiologia.setSelectedItem("");
                jComboBoxPsicologia.setSelectedItem("");
                jComboBoxTherasuit.setSelectedItem("");
                jComboBoxMusicoterapia.setSelectedItem("");
                jComboBoxEstimulacaoVisual.setSelectedItem("");
                jTextFieldNomePaciente.setEnabled(false);
                jFormattedTextFieldCpf_paciente.setEnabled(false);
                jTextFieldRg_paciente.setEnabled(false);
                jFormattedTextFieldData_de_nascimento_paciente.setEnabled(false);
                jFormattedTextFieldTelefonePaciente.setEnabled(false);
                jComboBoxParentesco_filiaçao1.setEnabled(false);
                jComboBoxParentesco_filiaçao2.setEnabled(false);
                jComboBoxDadosPaciente.setEnabled(false);
                jFormattedTextFieldTel_Filiaçao1.setEnabled(false);
                jFormattedTextFieldTel_filiaçao2.setEnabled(false);
                jTextFieldNome_Filiaçao1.setEnabled(false);
                jTextFieldNome_Filiaçao2.setEnabled(false);
                jTextFieldEndereçoPaciente.setEnabled(false);
                jTextFieldComplementoPaciente.setEnabled(false);
                jTextFieldBairroPaciente.setEnabled(false);
                jTextFieldCidade_paciente.setEnabled(false);
                jComboBoxEstado.setEnabled(false);                
                jComboBoxFisioterapia.setEnabled(false);
                jComboBoxTerapiaOcupacional.setEnabled(false);
                jComboBoxFonoaudiologia.setEnabled(false);
                jComboBoxPsicologia.setEnabled(false);
                jComboBoxTherasuit.setEnabled(false);
                jComboBoxMusicoterapia.setEnabled(false);
                jComboBoxEstimulacaoVisual.setEnabled(false);
                jButtonSalvar.setEnabled(false);
                jButtonNovo.setEnabled(true);
                jButtonCancelar.setEnabled(false);
                preencherTabelaPacientes("select *from pacientes order by nome_paciente");
            }
        } catch (SQLException ex) {
            //Logger.getLogger(FormFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNomePaciente.setEnabled(true);
        jFormattedTextFieldCpf_paciente.setEnabled(true);
        jTextFieldRg_paciente.setEnabled(true);
        jFormattedTextFieldData_de_nascimento_paciente.setEnabled(true);
        jFormattedTextFieldTelefonePaciente.setEnabled(true);
        jComboBoxParentesco_filiaçao1.setEnabled(true);
        jComboBoxParentesco_filiaçao2.setEnabled(true);
        jComboBoxDadosPaciente.setEnabled(true);
        jFormattedTextFieldTel_Filiaçao1.setEnabled(true);
        jFormattedTextFieldTel_filiaçao2.setEnabled(true);
        jTextFieldNome_Filiaçao1.setEnabled(true);
        jTextFieldNome_Filiaçao2.setEnabled(true);
        jTextFieldEndereçoPaciente.setEnabled(true);
        jTextFieldComplementoPaciente.setEnabled(true);
        jTextFieldBairroPaciente.setEnabled(true);
        jTextFieldCidade_paciente.setEnabled(true);
        jComboBoxEstado.setEnabled(true);
        jComboBoxFisioterapia.setEnabled(true);
        jComboBoxTerapiaOcupacional.setEnabled(true);
        jComboBoxFonoaudiologia.setEnabled(true);
        jComboBoxPsicologia.setEnabled(true);
        jComboBoxTherasuit.setEnabled(true);
        jComboBoxMusicoterapia.setEnabled(true);
        jComboBoxEstimulacaoVisual.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTabelaPacientes("select *from pacientes");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta= 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if(resposta == JOptionPane.YES_OPTION){
            mod.setCodigo(Integer.parseInt(jTextFieldCodPaciente.getText()));
            control.Excluir(mod);
            jTextFieldNomePaciente.setText("");
            jFormattedTextFieldCpf_paciente.setText("");
            jTextFieldRg_paciente.setText("");
            jFormattedTextFieldData_de_nascimento_paciente.setText("");
            jFormattedTextFieldTelefonePaciente.setText("");
            jComboBoxParentesco_filiaçao1.setSelectedItem("");
            jComboBoxParentesco_filiaçao2.setSelectedItem("");
            jComboBoxDadosPaciente.setSelectedItem("");
            jFormattedTextFieldTel_Filiaçao1.setText("");
            jFormattedTextFieldTel_filiaçao2.setText("");
            jTextFieldNome_Filiaçao1.setText("");
            jTextFieldNome_Filiaçao2.setText("");
            jTextFieldEndereçoPaciente.setText("");
            jTextFieldComplementoPaciente.setText("");
            jTextFieldBairroPaciente.setText("");
            jTextFieldCidade_paciente.setText("");
            jComboBoxEstado.setSelectedItem("");            
            jComboBoxFisioterapia.setSelectedItem("");
            jComboBoxTerapiaOcupacional.setSelectedItem("");
            jComboBoxFonoaudiologia.setSelectedItem("");
            jComboBoxPsicologia.setSelectedItem("");
            jComboBoxTherasuit.setSelectedItem("");
            jComboBoxMusicoterapia.setSelectedItem("");
            jComboBoxEstimulacaoVisual.setSelectedItem("");
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonExcluir.setEnabled(false); 
            preencherTabelaPacientes("select *from pacientes order by nome_paciente");
       }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNomePaciente.setEnabled(!true);
        jFormattedTextFieldCpf_paciente.setEnabled(!true);
        jTextFieldRg_paciente.setEnabled(!true);
        jFormattedTextFieldData_de_nascimento_paciente.setEnabled(!true);
        jFormattedTextFieldTelefonePaciente.setEnabled(!true);
        jComboBoxParentesco_filiaçao1.setEnabled(!true);
        jComboBoxParentesco_filiaçao2.setEnabled(!true);
        jComboBoxDadosPaciente.setEnabled(!true);
        jFormattedTextFieldTel_Filiaçao1.setEnabled(!true);
        jFormattedTextFieldTel_filiaçao2.setEnabled(!true);
        jTextFieldNome_Filiaçao1.setEnabled(!true);
        jTextFieldNome_Filiaçao2.setEnabled(!true);
        jTextFieldEndereçoPaciente.setEnabled(!true);
        jTextFieldComplementoPaciente.setEnabled(!true);
        jTextFieldBairroPaciente.setEnabled(!true);
        jTextFieldCidade_paciente.setEnabled(!true);
        jComboBoxEstado.setEnabled(!true);
        jComboBoxFisioterapia.setEnabled(!true);
        jComboBoxTerapiaOcupacional.setEnabled(!true);
        jComboBoxFonoaudiologia.setEnabled(!true);
        jComboBoxPsicologia.setEnabled(!true);
        jComboBoxTherasuit.setEnabled(!true);
        jComboBoxMusicoterapia.setEnabled(!true);
        jComboBoxEstimulacaoVisual.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jFormattedTextFieldCpf_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCpf_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCpf_pacienteActionPerformed

    private void jTablePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacientesMouseClicked
        String nome_paciente = "" + jTablePacientes.getValueAt(jTablePacientes.getSelectedRow(), 1);
        connBanco.conexao();
        connBanco.executaSQL("select *from pacientes where nome_paciente='"+nome_paciente+"'");
        try {
            connBanco.rs.first();
            jTextFieldCodPaciente.setText(String.valueOf(connBanco.rs.getInt("cod_paciente")));
            jTextFieldNomePaciente.setText(connBanco.rs.getString("nome_paciente")); 
            jFormattedTextFieldData_de_nascimento_paciente.setText(connBanco.rs.getString("data_de_nascimento_paciente"));
            jComboBoxFisioterapia.setSelectedItem(connBanco.rs.getString("fisio_paciente"));
            jComboBoxTerapiaOcupacional.setSelectedItem(connBanco.rs.getString("to_paciente"));
            jComboBoxFonoaudiologia.setSelectedItem(connBanco.rs.getString("fono_paciente"));
            jComboBoxPsicologia.setSelectedItem(connBanco.rs.getString("psi_paciente"));
            jComboBoxTherasuit.setSelectedItem(connBanco.rs.getString("therasuit_paciente"));
            jComboBoxMusicoterapia.setSelectedItem(connBanco.rs.getString("musicoterapia_paciente"));
            jComboBoxEstimulacaoVisual.setSelectedItem(connBanco.rs.getString("estimulacaovisual_paciente"));
            jTextFieldNome_Filiaçao1.setText(connBanco.rs.getString("filiacao_1"));
            jFormattedTextFieldTel_Filiaçao1.setText(connBanco.rs.getString("tel_filiacao_1"));
            jComboBoxParentesco_filiaçao1.setSelectedItem(connBanco.rs.getString("parentesco_filiacao_1"));
            jTextFieldNome_Filiaçao2.setText(connBanco.rs.getString("filiacao_2"));
            jFormattedTextFieldTel_filiaçao2.setText(connBanco.rs.getString("tel_filiacao_2"));
            jComboBoxParentesco_filiaçao2.setSelectedItem(connBanco.rs.getString("parentesco_filiacao_2"));
            jComboBoxDadosPaciente.setSelectedItem(connBanco.rs.getString("dados_relatorio"));
            jFormattedTextFieldCpf_paciente.setText(connBanco.rs.getString("cpf_paciente"));
            jTextFieldRg_paciente.setText(connBanco.rs.getString("rg_paciente"));
            jFormattedTextFieldTelefonePaciente.setText(connBanco.rs.getString("telefone_paciente"));        
            jTextFieldEndereçoPaciente.setText(connBanco.rs.getString("endereco_paciente"));
            jTextFieldComplementoPaciente.setText(connBanco.rs.getString("complemento_paciente"));
            jTextFieldBairroPaciente.setText(connBanco.rs.getString("bairro_paciente"));
            jTextFieldCidade_paciente.setText(connBanco.rs.getString("cidade_paciente"));
            jComboBoxEstado.setSelectedItem(connBanco.rs.getString("estado_paciente"));
            connBanco.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar os dados!\nERRO:" + ex);
        }
        connBanco.desconecta();
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jTablePacientesMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisar(jTextFieldPesquisar.getText());
        BeansPacientes model = control.buscaPacientes(mod);
        jTextFieldCodPaciente.setText(String.valueOf(model.getCodigo()));
        jTextFieldNomePaciente.setText(model.getNome()); 
        jFormattedTextFieldData_de_nascimento_paciente.setText(model.getDatadenascimento());
        jComboBoxFisioterapia.setSelectedItem(model.getQntdFisio());
        jComboBoxTerapiaOcupacional.setSelectedItem(model.getQntdTO());
        jComboBoxFonoaudiologia.setSelectedItem(model.getQntdFono());
        jComboBoxPsicologia.setSelectedItem(model.getQntdPsi());
        jComboBoxTherasuit.setSelectedItem(model.getQntdTherasuit());
        jComboBoxMusicoterapia.setSelectedItem(model.getQntdMusicoterapia());
        jComboBoxEstimulacaoVisual.setSelectedItem(model.getQntdEstVisual());
        jTextFieldNome_Filiaçao1.setText(model.getFiliacao_1());
        jFormattedTextFieldTel_Filiaçao1.setText(model.getTel_fil_1());
        jComboBoxParentesco_filiaçao1.setSelectedItem(model.getParentesco_1());
        jTextFieldNome_Filiaçao2.setText(model.getFiliacao_2());
        jFormattedTextFieldTel_filiaçao2.setText(model.getTel_fil_2());
        jComboBoxParentesco_filiaçao2.setSelectedItem(model.getParentesco_2());
        jComboBoxDadosPaciente.setSelectedItem(model.getDados());
        jFormattedTextFieldCpf_paciente.setText(model.getCpf());
        jTextFieldRg_paciente.setText(model.getRg());
        jFormattedTextFieldTelefonePaciente.setText(model.getTelefone());
        jTextFieldEndereçoPaciente.setText(model.getEndereço());
        jTextFieldComplementoPaciente.setText(model.getComplemento());
        jTextFieldBairroPaciente.setText(model.getBairro());
        jTextFieldCidade_paciente.setText(model.getCidade());
        jComboBoxEstado.setSelectedItem(model.getEstado());
        preencherTabelaPacientes("select *from pacientes where nome_paciente like'%" + jTextFieldPesquisar.getText() +"%'");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    
    public void preencherTabelaPacientes(String Sql){
            
        ArrayList dados = new ArrayList();
        String[] colunas = new String[] {"Cod.", "Nome Paciente", "Data de Nascimento", "Fisioterapia", "Terapia Ocupacional", "Fonoaudiologia", "Psicologia", "Therasuit", "Musicoterapia", "Estimulação Visual", "filiacao_1", "tel_filiacao_1", "parentesco_filiacao_1", "filiacao_2", "tel_filiacao_2", "parentesco_filiacao_2","dados_relatorio","cpf_paciente","rg_paciente","telefone_paciente","endereço_paciente","complemento_paciente","bairro_paciente","cidade_paciente","estado_paciente"};
        connBanco.conexao();
        connBanco.executaSQL(Sql);
        try{
            connBanco.rs.first();
            do{
                dados.add(new Object[]{connBanco.rs.getInt("cod_paciente"),connBanco.rs.getString("nome_paciente"),connBanco.rs.getString("data_de_nascimento_paciente"),connBanco.rs.getString("fisio_paciente"),connBanco.rs.getString("to_paciente"),connBanco.rs.getString("fono_paciente"),connBanco.rs.getString("psi_paciente"),connBanco.rs.getString("therasuit_paciente"),connBanco.rs.getString("musicoterapia_paciente"),connBanco.rs.getString("estimulacaovisual_paciente"),connBanco.rs.getString("filiacao_1"),connBanco.rs.getString("tel_filiacao_1"),connBanco.rs.getString("parentesco_filiacao_1"),connBanco.rs.getString("filiacao_2"),connBanco.rs.getString("tel_filiacao_2"),connBanco.rs.getString("parentesco_filiacao_2"),connBanco.rs.getString("dados_relatorio"),connBanco.rs.getString("cpf_paciente"),connBanco.rs.getString("rg_paciente"),connBanco.rs.getString("telefone_paciente"),connBanco.rs.getString("endereco_paciente"),connBanco.rs.getString("complemento_paciente"),connBanco.rs.getString("bairro_paciente"),connBanco.rs.getString("cidade_paciente"),connBanco.rs.getString("estado_paciente")});
                
            }while(connBanco.rs.next());
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayListPac" + ex);
        }
        ModeloTabela modelo= new ModeloTabela(dados, colunas);
        
        jTablePacientes.setModel(modelo);
        jTablePacientes.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTablePacientes.getColumnModel().getColumn(0).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTablePacientes.getColumnModel().getColumn(1).setResizable(false);        
        jTablePacientes.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(2).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(3).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(3).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(4).setResizable(false);    
        jTablePacientes.getColumnModel().getColumn(5).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(5).setResizable(false);        
        jTablePacientes.getColumnModel().getColumn(6).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(6).setResizable(false);        
        jTablePacientes.getColumnModel().getColumn(7).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(7).setResizable(false);        
        jTablePacientes.getColumnModel().getColumn(8).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(8).setResizable(false);        
        jTablePacientes.getColumnModel().getColumn(9).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(9).setResizable(false);        
        jTablePacientes.getColumnModel().getColumn(10).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(10).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(11).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(11).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(12).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(12).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(13).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(13).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(14).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(14).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(15).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(15).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(16).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(16).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(17).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(17).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(18).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(18).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(19).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(19).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(20).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(20).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(21).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(21).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(22).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(22).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(23).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(23).setResizable(false);
        jTablePacientes.getColumnModel().getColumn(24).setPreferredWidth(130);
        jTablePacientes.getColumnModel().getColumn(24).setResizable(false);
        jTablePacientes.getTableHeader().setReorderingAllowed(false);
        jTablePacientes.setAutoResizeMode(jTablePacientes.AUTO_RESIZE_OFF);        
        jTablePacientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        connBanco.desconecta();
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxDadosPaciente;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxEstimulacaoVisual;
    private javax.swing.JComboBox<String> jComboBoxFisioterapia;
    private javax.swing.JComboBox<String> jComboBoxFonoaudiologia;
    private javax.swing.JComboBox<String> jComboBoxMusicoterapia;
    private javax.swing.JComboBox<String> jComboBoxParentesco_filiaçao1;
    private javax.swing.JComboBox<String> jComboBoxParentesco_filiaçao2;
    private javax.swing.JComboBox<String> jComboBoxPsicologia;
    private javax.swing.JComboBox<String> jComboBoxTerapiaOcupacional;
    private javax.swing.JComboBox<String> jComboBoxTherasuit;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf_paciente;
    private javax.swing.JFormattedTextField jFormattedTextFieldData_de_nascimento_paciente;
    private javax.swing.JFormattedTextField jFormattedTextFieldTel_Filiaçao1;
    private javax.swing.JFormattedTextField jFormattedTextFieldTel_filiaçao2;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefonePaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBairroPaciente;
    private javax.swing.JLabel jLabelCidade_paciente;
    private javax.swing.JLabel jLabelComplemento_paciente;
    private javax.swing.JLabel jLabelCpf_paciente;
    private javax.swing.JLabel jLabelDadosPaciente;
    private javax.swing.JLabel jLabelEndereço_paciente;
    private javax.swing.JLabel jLabelEstado_paciente;
    private javax.swing.JLabel jLabelNome_Filiaçao1;
    private javax.swing.JLabel jLabelNome_Filiaçao2;
    private javax.swing.JLabel jLabelParentesco_filiaçao1;
    private javax.swing.JLabel jLabelParentesco_filiaçao2;
    private javax.swing.JLabel jLabelRg_paciente;
    private javax.swing.JLabel jLabelTel_Filiaçao1;
    private javax.swing.JLabel jLabelTel_Filiaçao2;
    private javax.swing.JLabel jLabelTel_paciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JTextField jTextFieldBairroPaciente;
    private javax.swing.JTextField jTextFieldCidade_paciente;
    private javax.swing.JTextField jTextFieldCodPaciente;
    private javax.swing.JTextField jTextFieldComplementoPaciente;
    private javax.swing.JTextField jTextFieldEndereçoPaciente;
    private javax.swing.JTextField jTextFieldNomePaciente;
    private javax.swing.JTextField jTextFieldNome_Filiaçao1;
    private javax.swing.JTextField jTextFieldNome_Filiaçao2;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldRg_paciente;
    // End of variables declaration//GEN-END:variables
}
