/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modeloConection.ConectarNoBanco;

/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {

        ConectarNoBanco connBanco = new ConectarNoBanco();
        FormFuncionarios telaFunc = new FormFuncionarios();
        FormPacientes telaPac = new FormPacientes();
        FormUsuario telaUsu = new FormUsuario();
        FormPesquisaPaciente telaPesqPac = new FormPesquisaPaciente();
        FormAgendamento telaAgendamento = new FormAgendamento();
        
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(String usuario) {
        initComponents();
        jLabelUsuario.setText(usuario);
        connBanco.conexao();
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuPacientes = new javax.swing.JMenu();
        jMenuItemPesquisar_pacientes = new javax.swing.JMenuItem();
        jMenuItemCadastrar_pacientes = new javax.swing.JMenuItem();
        jMenuItemAgendamento = new javax.swing.JMenuItem();
        jMenuFuncionarios = new javax.swing.JMenu();
        jMenuItemPesquisar_funcionarios = new javax.swing.JMenuItem();
        jMenuItemCadastrar_funcionarios = new javax.swing.JMenuItem();
        jMenuItemCadUsuarios = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Therapias - Habilitação Pediátrica");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Usuário:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 460, 50, 15);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUsuario.setText("jLabel3");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(60, 460, 200, 15);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_principal_verde.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 870, 480);

        jMenuCadastros.setText("Cadastros");

        jMenuPacientes.setText("Pacientes");

        jMenuItemPesquisar_pacientes.setText("Pesquisar");
        jMenuItemPesquisar_pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisar_pacientesActionPerformed(evt);
            }
        });
        jMenuPacientes.add(jMenuItemPesquisar_pacientes);

        jMenuItemCadastrar_pacientes.setText("Cadastrar");
        jMenuItemCadastrar_pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrar_pacientesActionPerformed(evt);
            }
        });
        jMenuPacientes.add(jMenuItemCadastrar_pacientes);

        jMenuItemAgendamento.setText("Agendamento");
        jMenuItemAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendamentoActionPerformed(evt);
            }
        });
        jMenuPacientes.add(jMenuItemAgendamento);

        jMenuCadastros.add(jMenuPacientes);

        jMenuFuncionarios.setText("Funcionários");

        jMenuItemPesquisar_funcionarios.setText("Pesquisar");
        jMenuFuncionarios.add(jMenuItemPesquisar_funcionarios);

        jMenuItemCadastrar_funcionarios.setText("Cadastrar");
        jMenuItemCadastrar_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrar_funcionariosActionPerformed(evt);
            }
        });
        jMenuFuncionarios.add(jMenuItemCadastrar_funcionarios);

        jMenuCadastros.add(jMenuFuncionarios);

        jMenuItemCadUsuarios.setText("Usuários");
        jMenuItemCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadUsuarios);

        jMenuBar1.add(jMenuCadastros);

        jMenuRelatorios.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(889, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrar_pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrar_pacientesActionPerformed
        try {
                connBanco.executaSQL("select *from usuarios where nome_usuario='"+jLabelUsuario.getText()+"'");
                connBanco.rs.first();
                if(connBanco.rs.getString("tipo_usuario").equals("Recepção")||(connBanco.rs.getString("tipo_usuario").equals("ADS"))){                    
                    if(telaPac==null){
                        telaPac = new FormPacientes();
                        telaPac.setVisible(true);
                        telaPac.setResizable(false);                    
                    }else{
                        telaPac.setVisible(true);
                        telaPac.setResizable(false);
                    }
//                    FormPacientes tela = new FormPacientes();
//                    tela.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o administrador do sistema!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o administrador do sistema!"+ex);
            }
    }//GEN-LAST:event_jMenuItemCadastrar_pacientesActionPerformed

    private void jMenuItemCadastrar_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrar_funcionariosActionPerformed
        
            try {
                connBanco.executaSQL("select *from usuarios where nome_usuario='"+jLabelUsuario.getText()+"'");
                connBanco.rs.first();
                if(connBanco.rs.getString("tipo_usuario").equals("Administrativo")||(connBanco.rs.getString("tipo_usuario").equals("ADS"))){
                    if(telaFunc==null){
                        telaFunc = new FormFuncionarios();
                        telaFunc.setVisible(true);
                        telaFunc.setResizable(false);                    
                    }else{
                        telaFunc.setVisible(true);
                        telaFunc.setResizable(false);
                    }
//                    FormFuncionarios tela = new FormFuncionarios();
//                    tela.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o administrador do sistema!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o administrador do sistema!"+ex);
            }
    }//GEN-LAST:event_jMenuItemCadastrar_funcionariosActionPerformed

    private void jMenuItemPesquisar_pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisar_pacientesActionPerformed
        FormPesquisaPaciente tela = new FormPesquisaPaciente();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisar_pacientesActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuItemCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuariosActionPerformed
        try {
                connBanco.executaSQL("select *from usuarios where nome_usuario='"+jLabelUsuario.getText()+"'");
                connBanco.rs.first();
                if(connBanco.rs.getString("tipo_usuario").equals("ADS")){                    
                    if(telaUsu==null){
                        telaUsu = new FormUsuario();
                        telaUsu.setVisible(true);
                        telaUsu.setResizable(false);
                        
                    }else{
                        telaUsu.setVisible(true);
                        telaUsu.setResizable(false);
                    }
//                    FormUsuario tela = new FormUsuario();
//                    tela.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o administrador do sistema!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o administrador do sistema!"+ex);
            }
    }//GEN-LAST:event_jMenuItemCadUsuariosActionPerformed

    private void jMenuItemAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendamentoActionPerformed
        try {
                connBanco.executaSQL("select *from usuarios where nome_usuario='"+jLabelUsuario.getText()+"'");
                connBanco.rs.first();
                if(connBanco.rs.getString("tipo_usuario").equals("Recepção")||(connBanco.rs.getString("tipo_usuario").equals("ADS"))){
                    if(telaAgendamento==null){
                        telaAgendamento = new FormAgendamento();
                        telaAgendamento.setVisible(true);
                        telaAgendamento.setResizable(false);                    
                    }else{
                        telaAgendamento.setVisible(true);
                        telaAgendamento.setResizable(false);
                    }
//                    FormFuncionarios tela = new FormFuncionarios();
//                    tela.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o administrador do sistema!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissão para essa funcionalidade!\n Contate o administrador do sistema!"+ex);
            }
    }//GEN-LAST:event_jMenuItemAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuFuncionarios;
    private javax.swing.JMenuItem jMenuItemAgendamento;
    private javax.swing.JMenuItem jMenuItemCadUsuarios;
    private javax.swing.JMenuItem jMenuItemCadastrar_funcionarios;
    private javax.swing.JMenuItem jMenuItemCadastrar_pacientes;
    private javax.swing.JMenuItem jMenuItemPesquisar_funcionarios;
    private javax.swing.JMenuItem jMenuItemPesquisar_pacientes;
    private javax.swing.JMenu jMenuPacientes;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
